#!/bin/sh

dir="$HOME/data/movie-tracker"

if [ ! -d "$dir" ]
then
	mkdir -p "$dir"
	if [ $? -ne 0 ]
	then
		echo "Creation of $dir failed. Quitting."
		exit
	fi
fi

printf "What movie did you see? "
read title
printf "When did you see it? "
read date
printf "Who is the director? "
read director
printf "When was the film originally released? " 
read release
printf "What is the director's country? " 
read country

echo "Where did you see the movie?"

test ! -f "$dir/movies.csv" ||
list=$(sed -n 's/".*"//;/^\(\t\|\n\| \)*$/d;2,$p' "$dir/movies.csv" | cut -s -d, -f6 | sort -u | sed 's/\(^\|$\)/"/g' | tr "\n" " ")

eval "set -- $list"
i=1
for cinema; do
	printf "\t%2d) $cinema\n" $i
	i=$(($i+1))
done
printf "\t$i) Other\n"

read option

# To add a range limit.

while ! expr $option : '^[1-9][0-9]*$' > /dev/null
do
	printf "Choose a valid number (1-$i): "
	read option
done

if [ $option -lt $i ]
then
	cinema=$(eval "echo $(echo "$"$option)")
else
	printf "Where? "
	read cinema
fi

printf "Rating? " 
read rating

echo "$date,$title,$director,$release,$country,$cinema,$rating" >> $HOME/data/movie-tracker/movies.csv
