#!/bin/sh

message="Time is up!"

case $1 in

	-p)		i=5 ;;
	*)		i=25 ;;
esac

while [ "$i" -ne 0 ]; do 
	printf "Time remaining: $i"
	sleep 60
	printf "\033[2K\r"
	i=$(($i-1))
done

if command -v notify-send > /dev/null
then
	notify-send "$message"
fi

printf "$message\a"
