#!/bin/sh

message="Time is up!"

i=25
while [ "$i" -ne 0 ]; do 
	printf "Time remaining: $i"
	sleep 60
	printf "\033[2K\r"
	i=$(expr "$i" - 1)
done

if command -v notify-send > /dev/null 2>&1
then
	notify-send "$message"
fi

printf "$message\a"
