#!/bin/sh

dir="$HOME/data/rfcs"

error()
{
	echo "$1 Quitting."
	exit 1
}

if [ ! -d "$dir" ]
then
	mkdir -p $dir
	if [ $? -ne 0 ]
	then
		error "Directory $dir could not be created."
	else	
		echo "$dir created."
	fi
fi

echo "Available RFCs:"
ls $dir

printf "Which RFC do you want to read? "
read rfc

rfc="rfc$rfc.txt"
url="https://www.rfc-editor.org/rfc/$rfc"
path="$dir/$rfc"

if [ ! -f $path ]
then
	if $(command -v wget > /dev/null)
	then
		wget -qP $dir $url
		if [ $? -ne 0 ]; then error "Invalid RFC number."; fi	
	else
		error "wget is needed to download new RFCs."
	fi
fi	

more $path
